### ISSUE TITLE
Lightbox doesn't work in IE11 once minified

### ISSUE THREAD

**Issue by losbeekos** [mcstudios/glightbox#31] opened 2018-09-19 06:10 UTC
In IE11 the following error is thrown on a production/minified build:

`multiple definitions of a property not allowed in strict mode`.

I forked the package and deleted the 'use strict' line so it will work for now but I think we need a proper solution :).

**Comment by alinnert** [comment] 2018-09-20 08:47
I'm experiencing the same issue but with a different error: `The object doesn't support the property or method "addEventListener".` When I debug the error to find out what "the object" is, it turns out to be a `forEach` function with `native code` in its body. So, it's calling `forEach.addEventListener()`?

I've tried to find the cause of the error by commenting out each of my modules. I was able to get rid of the error by just commenting out the line:

~~~
this.lightbox = GLightbox({})
~~~

I'm also bundling my code using Babel 7.0.1, Webpack 4.19.0 and GLightbox 1.0.6 (It seems 1.0.7 isn't published on npm yet)

**Comment by mcstudios** [comment] 2018-10-15 18:34
I've fixed some issues with IE11 but I was not able to replicate the same errors you mention.

Please try the latest version and if you still see the errors please provide a live example so I can take a look.

**Comment by mcstudios** [comment] 2018-10-16 15:43
Hi @alinnert  
If you check the dist folder you'll see a minified version of Glightbox using gulp-uglify which uses UglifyJS under the hood.

Did you try the minified version available in the dist folder? if so, do you get the same error?

I don't use Webpack so I'm not sure how the code is minified so if Webpack's minimization is causing the issue then I'm gonna need some help to "solve" this.

**Comment by alinnert** [comment] 2018-10-16 19:11
Webpack uses [`uglify-es`](https://github.com/mishoo/UglifyJS2/tree/harmony) by default - which seems to be a ES6+ compatible branch (not a fork) of uglify-js itself. (I also didn't know that until now). But I can't find any default options being used or set by Webpack or its UglifyJsPlugin.

I can't really use your minified version. One option would be to serve it separately. This defeates the purpose of Webpack and also makes it harder to use from inside my webpack-based scripts. The second option is to disable uglifying, which is not a good idea. But maybe I can override the default `uglify-es` with a custom `uglify-js` minification using settings that also work for you. But this shouldn't be necessary.

Maybe you can find the error by using uglify-es instead of uglify-js to minify GLightbox.

**Comment by mcstudios** [comment] 2018-12-04 11:13
@alinnert it seems that uglify-es is no longer maintained https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058

**Comment by alinnert** [comment] 2018-12-04 14:24
@mcstudios yes, and according to [this reddit post](https://www.reddit.com/r/javascript/comments/a2pq73/support_terser_js_minifier_do_not_let_the_history/) neither UglifyJS nor uglify-es aren't maintained anymore. The current successor seems to be [Terser](https://github.com/terser-js/terser) - Webpack also uses Terser now. I've replaced uglify-es with terser in one project and the options seem to be pretty much identical.

**Comment by mcstudios** [comment] 2018-12-04 17:34
@alinnert i'll try Terser and check what's happening.

**Comment by mcstudios** [comment] 2018-12-05 15:33
@alinnert I did some changes, the code is now minified with terser, updated some code to fix the errors on ie11, if you have some free time please try it and let me know if it works.

**Comment by alinnert** [comment] 2018-12-11 07:15
@mcstudios Yes, it works now. Thank you.

The only thing is: IE doesn't scale down the image if it's too big. But I found a way to fix that:

Replace:

~~~ css
.gslide-image img {
  max-width: 100%;
}
~~~

...with:

~~~ css
.gslide-image img {
  max-width: 100vw; /* *) */
  height: auto; /* otherwise IE stretches the image */
}
~~~

This doesn't seem to break Chrome and Firefox.

*) *I know, `100%` and `100vw` are different because `100vw` includes the with of the scrollbar, but there are none in the overlay. So it should be fine.*

**Comment by mcstudios** [comment] 2018-12-11 16:26
Awesome. I'll try your fix with more browsers and mobile and if everything looks good i'll include it in the next update. I'm gonna close this issue for now as we are moving away from the original issue, feel free to open new issues if you find a bug.

**Closed by mcstudios** 2018-12-11 16:26 UTC
